# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time_slot', models.CharField(choices=[('6', '6:00 am'), ('7', '7:00 am'), ('8', '8:00 am'), ('9', '9:00 am'), ('10', '10:00 am'), ('11', '11:00 am'), ('12', '12:00 am'), ('13', '1: 00 pm'), ('14', '2: 00 pm'), ('15', '3: 00 pm'), ('16', '4: 00 pm'), ('17', '5: 00 pm'), ('18', '6: 00 pm')], max_length=2)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mama.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.FileField(default='default.jpg', null=True, upload_to='images')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.Doctor')),
            ],
            options={
                'verbose_name_plural': 'Doctor reviews',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('specialty', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Doctors specialties',
            },
        ),
        migrations.CreateModel(
            name='DoctorWorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_from', models.CharField(choices=[('6', '6:00 am'), ('7', '7:00 am'), ('8', '8:00 am'), ('9', '9:00 am'), ('10', '10:00 am'), ('11', '11:00 am'), ('12', '12:00 am'), ('13', '1: 00 pm'), ('14', '2: 00 pm'), ('15', '3: 00 pm'), ('16', '4: 00 pm'), ('17', '5: 00 pm'), ('18', '6: 00 pm')], max_length=2)),
                ('working_to', models.CharField(choices=[('6', '6:00 am'), ('7', '7:00 am'), ('8', '8:00 am'), ('9', '9:00 am'), ('10', '10:00 am'), ('11', '11:00 am'), ('12', '12:00 am'), ('13', '1: 00 pm'), ('14', '2: 00 pm'), ('15', '3: 00 pm'), ('16', '4: 00 pm'), ('17', '5: 00 pm'), ('18', '6: 00 pm')], max_length=2)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='mama.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='LiveChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField()),
                ('pinned_message', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='default.jpg', null=True, upload_to='images')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('grams', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='mama.Medication')),
            ],
            options={
                'verbose_name_plural': 'Medications Prices',
            },
        ),
        migrations.CreateModel(
            name='MidWife',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.FileField(default='default.jpg', null=True, upload_to='images')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MidWifeSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'MidWifes specialties',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.FileField(default='default.jpg', null=True, upload_to='images')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=8, unique=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('doctors', models.ManyToManyField(to='mama.Doctor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('length', models.IntegerField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.Medication')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('live', models.NullBooleanField()),
                ('absorved', models.NullBooleanField()),
                ('inactivated', models.NullBooleanField()),
                ('oral', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VaccineApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.MidWife')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.Patient')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.Vaccine')),
            ],
            options={
                'verbose_name_plural': 'Vaccines usage',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=2000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.Visit'),
        ),
        migrations.AddField(
            model_name='midwife',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.MidWifeSpeciality'),
        ),
        migrations.AddField(
            model_name='livechat',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.Patient'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.DoctorSpeciality'),
        ),
        migrations.AddField(
            model_name='department',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(related_name='_department_staff_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='mama.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.Patient'),
        ),
    ]
