# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('6', '6:00 am'), ('7', '7:00 am'), ('8', '8:00 am'), ('9', '9:00 am'), ('10', '10:00 am'), ('11', '11:00 am'), ('12', '12:00 am'), ('13', '1:00 pm'), ('14', '2:00 pm'), ('15', '3:00 pm'), ('16', '4:00 pm'), ('17', '5:00 pm'), ('18', '6:00 pm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='working_from',
            field=models.CharField(choices=[('6', '6:00 am'), ('7', '7:00 am'), ('8', '8:00 am'), ('9', '9:00 am'), ('10', '10:00 am'), ('11', '11:00 am'), ('12', '12:00 am'), ('13', '1:00 pm'), ('14', '2:00 pm'), ('15', '3:00 pm'), ('16', '4:00 pm'), ('17', '5:00 pm'), ('18', '6:00 pm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='working_to',
            field=models.CharField(choices=[('6', '6:00 am'), ('7', '7:00 am'), ('8', '8:00 am'), ('9', '9:00 am'), ('10', '10:00 am'), ('11', '11:00 am'), ('12', '12:00 am'), ('13', '1:00 pm'), ('14', '2:00 pm'), ('15', '3:00 pm'), ('16', '4:00 pm'), ('17', '5:00 pm'), ('18', '6:00 pm')], max_length=20),
        ),
    ]
