# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('registration_number', models.CharField(max_length=100)),
                ('registration_date', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('postal_address', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('sub_speciality', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=100)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='mama.Doctor')),
            ],
        ),
    ]
