# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0002_auto_20181101_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medprice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
