# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0002_doctorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.DoctorSpeciality'),
        ),
    ]
