# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0003_auto_20181119_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.FileField(null=True, upload_to='profile_pictures'),
        ),
    ]
