# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0003_auto_20181101_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Doctor reviews',
            },
        ),
        migrations.CreateModel(
            name='LiveChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField()),
                ('pinned_message', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='midwife',
            name='photo',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(to='mama.Doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='medprice',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='mama.Medication'),
        ),
        migrations.AddField(
            model_name='livechat',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.Doctor'),
        ),
        migrations.AddField(
            model_name='livechat',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.Patient'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.Doctor'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mama.Patient'),
        ),
    ]
