# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0004_auto_20181101_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor',
            new_name='doctors',
        ),
    ]
