# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0004_auto_20181119_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.FileField(default='default.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
