# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0007_auto_20181102_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='medication',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
