# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0007_auto_20181102_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
                ('time_slot', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='mama.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mama.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availabe_from', models.TimeField()),
                ('availabe_to', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mama.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.FileField(default=None, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medication',
            name='grams',
            field=models.IntegerField(default=0),
        ),
    ]
