# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0008_auto_20181103_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
