# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0010_auto_20181104_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.FileField(default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.FileField(default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='midwife',
            name='photo',
            field=models.FileField(default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.FileField(default='default.jpg', null=True, upload_to='images'),
        ),
    ]
