# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0014_auto_20181104_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(),
        ),
    ]
