# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0019_auto_20181105_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='working_from',
            field=models.CharField(choices=[('6:00 am', '6:00 am'), ('7:00 am', '7:00 am'), ('8:00 am', '8:00 am'), ('9:00 am', '9:00 am'), ('10:00 am', '10:00 am'), ('11:00 am', '11:00 am'), ('12:00 am', '12:00 am'), ('13:00 pm', '1:00 pm'), ('14:00 pm', '2:00 pm'), ('15:00 pm', '3:00 pm'), ('16:00 pm', '4:00 pm'), ('17:00 pm', '5:00 pm'), ('18:00 pm', '6:00 pm:')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='working_to',
            field=models.CharField(choices=[('6:00 am', '6:00 am'), ('7:00 am', '7:00 am'), ('8:00 am', '8:00 am'), ('9:00 am', '9:00 am'), ('10:00 am', '10:00 am'), ('11:00 am', '11:00 am'), ('12:00 am', '12:00 am'), ('13:00 pm', '1:00 pm'), ('14:00 pm', '2:00 pm'), ('15:00 pm', '3:00 pm'), ('16:00 pm', '4:00 pm'), ('17:00 pm', '5:00 pm'), ('18:00 pm', '6:00 pm:')], max_length=20),
        ),
    ]
